# Directory Opus 5
# Copyright 1993-2012 Jonathan Potter & GP Software
# Copyright 2012-2013 DOPUS5 Open Source Team
# Copyright 2023-2026 Dimitris Panokostas

CC ?= cc
CFLAGS ?= -Wall -Wextra
TEST_BUILD_DIR ?= /tmp/dopus5-ftp-tests

FTP_PARSE_TEST := $(TEST_BUILD_DIR)/ftp_parse_tests
FTP_PARSE_TEST_SRCS := tests/ftp_parse_tests.c ftp_parse.c
FTP_LISTCMD_TEST := $(TEST_BUILD_DIR)/ftp_listcmd_tests
FTP_LISTCMD_TEST_SRCS := tests/ftp_listcmd_tests.c ftp_listcmd.c
FTP_TLS_TEST := $(TEST_BUILD_DIR)/ftp_tls_tests
FTP_TLS_TEST_SRCS := tests/ftp_tls_tests.c ftp_tls.c
FTP_PROTOCOL_TEST := $(TEST_BUILD_DIR)/ftp_protocol_tests
FTP_PROTOCOL_TEST_SRCS := tests/ftp_protocol_tests.c ftp_protocol.c
FTP_SFTP_TEST := $(TEST_BUILD_DIR)/ftp_sftp_tests
FTP_SFTP_TEST_SRCS := tests/ftp_sftp_tests.c ftp_sftp.c
FTP_SFTP_LIBSSH2_TEST := $(TEST_BUILD_DIR)/ftp_sftp_tests_libssh2
LIBSSH2_CFLAGS ?= $(shell pkg-config --cflags libssh2)
LIBSSH2_LIBS ?= $(shell pkg-config --libs libssh2)

.PHONY: test test-libssh2 clean

test: $(FTP_PARSE_TEST) $(FTP_LISTCMD_TEST) $(FTP_TLS_TEST) $(FTP_PROTOCOL_TEST) $(FTP_SFTP_TEST)
	$(FTP_PARSE_TEST)
	$(FTP_LISTCMD_TEST)
	$(FTP_TLS_TEST)
	$(FTP_PROTOCOL_TEST)
	$(FTP_SFTP_TEST)

test-libssh2: $(FTP_SFTP_LIBSSH2_TEST)
	$(FTP_SFTP_LIBSSH2_TEST)

$(FTP_PARSE_TEST): $(FTP_PARSE_TEST_SRCS) ftp_parse.h | $(TEST_BUILD_DIR)
	$(CC) $(CFLAGS) -I. $(FTP_PARSE_TEST_SRCS) -o $@

$(FTP_LISTCMD_TEST): $(FTP_LISTCMD_TEST_SRCS) ftp_listcmd.h | $(TEST_BUILD_DIR)
	$(CC) $(CFLAGS) -I. $(FTP_LISTCMD_TEST_SRCS) -o $@

$(FTP_TLS_TEST): $(FTP_TLS_TEST_SRCS) ftp_tls.h | $(TEST_BUILD_DIR)
	$(CC) $(CFLAGS) -I. $(FTP_TLS_TEST_SRCS) -o $@

$(FTP_PROTOCOL_TEST): $(FTP_PROTOCOL_TEST_SRCS) ftp_protocol.h | $(TEST_BUILD_DIR)
	$(CC) $(CFLAGS) -I. $(FTP_PROTOCOL_TEST_SRCS) -o $@

$(FTP_SFTP_TEST): $(FTP_SFTP_TEST_SRCS) ftp_sftp.h | $(TEST_BUILD_DIR)
	$(CC) $(CFLAGS) -I. $(FTP_SFTP_TEST_SRCS) -o $@

$(FTP_SFTP_LIBSSH2_TEST): $(FTP_SFTP_TEST_SRCS) ftp_sftp.h | $(TEST_BUILD_DIR)
	$(CC) $(CFLAGS) $(LIBSSH2_CFLAGS) -I. -DFTP_SFTP_BACKEND_LIBSSH2 -DFTP_SFTP_TESTING $(FTP_SFTP_TEST_SRCS) -o $@ $(LIBSSH2_LIBS)

$(TEST_BUILD_DIR):
	mkdir -p $@

clean:
	$(RM) $(FTP_PARSE_TEST) $(FTP_LISTCMD_TEST) $(FTP_TLS_TEST) $(FTP_PROTOCOL_TEST) $(FTP_SFTP_TEST) $(FTP_SFTP_LIBSSH2_TEST)
