name: Makefile CI

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
      - '[0-9]+.[0-9]+*'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - { name: os3, image: "sacredbanana/amiga-compiler:m68k-amigaos" }
          - { name: os4, image: "sacredbanana/amiga-compiler:ppc-amigaos" }
          - { name: mos, image: "sacredbanana/amiga-compiler:ppc-morphos" }
        variant:
          - { name: debug,   flags: "",          suffix: "_debug" }
          - { name: release, flags: "debug=no",  suffix: "" }

    name: build-${{ matrix.platform.name }}-${{ matrix.variant.name }}

    steps:
      - uses: actions/checkout@v6

      - name: Build (${{ matrix.platform.name }} ${{ matrix.variant.name }})
        run: |
          docker run --rm -v ${{ github.workspace }}:/work ${{ matrix.platform.image }} sh -c "cd /work/source && make ${{ matrix.platform.name }} release ${{ matrix.variant.flags }}"

      - uses: actions/upload-artifact@v7
        with:
          name: Dopus5_${{ matrix.platform.name }}${{ matrix.variant.suffix }}
          path: releases/Dopus5_*_${{ matrix.platform.name }}*.lha
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/Dopus5_*_os3.lha,artifacts/Dopus5_*_os4.lha,artifacts/Dopus5_*_mos.lha"
          generateReleaseNotes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
